###########################################################
#  COMMON SETTINGS                                        #
###########################################################
 debug_mode: false

###########################################################
# APPLICATION SETTINGS                                    #
###########################################################
 app_protocol: https
 app_host: iversity.org

 def_test_user: test@test.com
 def_test_pass: Test1234
 def_test_name: Auto Tester

###########################################################
# TEST ENVIRONMENTS SETTINGS                              #
###########################################################
 driver: selenium

############################################################
# TIMEOUTS                                                 #
############################################################
 timeout_tiny: 1
 timeout_short: 3
 timeout_small: 20
 timeout_medium: 60

